### ISSUE TITLE
Weird display of the pages after ../staff/

### ISSUE THREAD

**Issue by stormer1267** [OvercastTools/OvercastTools.github.io#4]
http://overcasttools.github.io/en/wiki/ranks/staff/mapdevelopmentstaff
http://overcasttools.github.io/en/wiki/ranks/staff/staff
http://overcasttools.github.io/en/wiki/ranks/staff/tournamentstaff

I don't know what I did wrong, I made those files on my desktop and then made a pull request and merged them into the master branch.

**Comment by nanuscience** [comment]
NO CSS ?

**Comment by matic0basle** [comment]
those pages shouldnt even exist. will fix it cause of the midunderstanding
